[package]
name = "square_eater"
version = "0.1.0"
authors = ["leudz <dylan.ancel@gmail.com>"]
edition = "2018"

[dependencies]
macroquad = { version = "0.3.0-alpha.14" }
shipyard = { path = "..", features = ["std"], default-features = false }