[package]
name = "square_eater"
version = "0.1.0"
authors = ["leudz <dylan.ancel@gmail.com>"]
edition = "2018"

[dependencies]
macroquad = "=0.3.0-alpha.15"
shipyard = { path = "..", features = ["proc", "std"], default-features = false }
sapp-wasm = "=0.1.20"
