[package]
name = "shipyard"
version = "0.2.0"
authors = ["leudz <dylan.ancel@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Entity Component System"
keywords = ["ecs", "entity", "component"]
categories = ["concurrency", "game-engines"]
readme = "README.md"
repository = "https://github.com/leudz/shipyard"

[workspace]
members = ["shipyard_proc"]

[dependencies]
num_cpus = {version = "1.11.1", optional = true}
rayon = {version = "1.2.1", optional = true}
shipyard_proc = { path = "./shipyard_proc", optional = true }
serde = {version = "1.0.104", optional = true}

[features]
default = ["parallel", "proc"]
parallel = ["rayon", "num_cpus"]
proc = ["shipyard_proc"]
serialization = ["serde"]

[dev-dependencies]
trybuild = "1.0.18"
serde_json = "1.0.44"