[package]
authors = ["leudz <dylan.ancel@gmail.com>"]
categories = ["data-structures", "game-development", "concurrency", "no-std"]
description = "Entity Component System"
edition = "2018"
keywords = ["ecs", "entity", "component"]
license = "MIT OR Apache-2.0"
name = "shipyard"
readme = "README.md"
repository = "https://github.com/leudz/shipyard"
version = "0.5.0"

[workspace]
members = ["bunny_demo", "shipyard_proc", "square_eater"]

[dependencies]
hashbrown = "0.11"
lock_api = "0.4"
rayon = { version = "1", optional = true }
serde = { version = "1", optional = true, default-features = false }
shipyard_proc = { version = "0.2", path = "./shipyard_proc", optional = true }
tracing = { version = "0.1", optional = true }

[features]
default = ["parallel", "std"]
parallel = ["rayon"]
proc = ["shipyard_proc"]
serde1 = ["serde"]
std = []
thread_local = ["std"]
tracing_info = ["parallel", "tracing"]

[dev-dependencies]
bincode = "1.3"
parking_lot = "0.11"
serde_json = "1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
