[package]
name = "shipyard"
version = "0.3.1"
authors = ["leudz <dylan.ancel@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Entity Component System"
keywords = ["ecs", "entity", "component"]
categories = ["concurrency", "game-engines"]
readme = "README.md"
repository = "https://github.com/leudz/shipyard"

[workspace]
members = ["shipyard_proc", "demo"]

[dependencies]
num_cpus = { version = "1.12.0", optional = true }
rayon = { version = "1.3.0", optional = true }
shipyard_proc = { version = "0.2.1", path = "./shipyard_proc", optional = true }
serde = { version = "1.0.104", optional = true, default-features = false }
parking_lot = { version = "0.10.0" }
hashbrown = "0.7.0"

[features]
default = ["parallel", "proc"]
parallel = ["rayon", "num_cpus", "std"]
proc = ["shipyard_proc"]
non_send = ["std"]
non_sync = ["std"]
std = []

[dev-dependencies]
trybuild = "1.0.23"
serde_json = "1.0.48"
