name: Book 

on: [push]

jobs:
  book:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v1

    - name: install mdbook 
      run: cargo install mdbook 

    - name: create dist directory 
      run: mkdir dist

    - name: build book
      run: cd book && mdbook build

    - name: copy book to dist
      run: cp -R ./book/output ./dist/book

    - name: deploy to gh_pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: "dist/"
        GH_PAT: ${{ secrets.GH_PAT }}
