name: Book and Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: create dist directory 
      run: mkdir dist

    - name: install rust
      run: rustup install stable

    - name: install mdbook 
      run: cargo install mdbook 

    - name: install node
      uses: actions/setup-node@v1

    - name: install npm deps
      run: npm ci
      working-directory: ./demo

    - name: add rust wasm target
      run: rustup target add wasm32-unknown-unknown

    - name: build book
      run: mdbook build
      working-directory: ./book

    - name: build demo 
      run: npm run build 
      working-directory: ./demo

    - name: copy book to dist
      run: cp -R ./book/output ./dist/book

    - name: copy demo to dist
      run: cp -R ./demo/public ./dist/demo

    - name: deploy to gh_pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: "dist/"
        GH_PAT: ${{ secrets.GH_PAT }}
