name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt

      - name: install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: miri

      - run: cargo +stable fmt -- --check

      - run: cargo +nightly miri test --no-default-features

      - run: cargo +stable clippy
        env:
          RUSTFLAGS: -D warnings

      - run: cargo +stable test --all-features
